apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aws-resource-watcher
  namespace: myapp
  labels:
    app: aws-resource-watcher
spec:
  serviceName: "aws-resource-watcher"
  replicas: 1
  selector:
    matchLabels:
      app: aws-resource-watcher
  template:
    metadata:
      labels:
        app: aws-resource-watcher
    spec:
      serviceAccountName: aws-resource-watcher
      
      containers:
      - name: aws-resource-watcher
        image: ghcr.io/mdminhazulhaque/aws-resource-watcher:latest
        imagePullPolicy: Always
        
        env:
        - name: KUBERNETES_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        
        envFrom:
        - configMapRef:
            name: aws-resource-watcher-config
        - secretRef:
            name: aws-resource-watcher-secret
            optional: true
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      
      securityContext:
        fsGroup: 65534
      
      restartPolicy: Always
