apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-resource-watcher-config
  namespace: myapp
data:
  # AWS Configuration
  AWS_REGION: "us-east-1"
  # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY can be set here for non-EKS clusters
  # For EKS with IAM service account, these are not needed
  
  # Region Configuration (optional)
  # REGIONS_INCLUDE: "us-east-1,us-west-2"
  # REGIONS_EXCLUDE: "ap-southeast-1,eu-west-1"
  
  # Redis Configuration
  REDIS_URI: "redis://aws-resource-watcher-redis:6379"
  
  # Monitoring Configuration
  SLEEP_INTERVAL_SECONDS: "300"
  
  # ARN Filter Configuration (optional)
  # ARN_IGNORE_PATTERNS: "arn:aws:s3:::*,arn:aws:logs:*:*:log-group:*"
  
  # SMTP Configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "your-email@gmail.com"
  SMTP_FROM_EMAIL: "your-email@gmail.com"
  SMTP_TO_EMAILS: "recipient1@example.com,recipient2@example.com"
  SMTP_USE_TLS: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-resource-watcher-secret
  namespace: myapp
type: Opaque
data:
  # Base64 encoded values
  # For non-EKS clusters, uncomment and set these:
  # AWS_ACCESS_KEY_ID: <base64-encoded-access-key>
  # AWS_SECRET_ACCESS_KEY: <base64-encoded-secret-key>
  
  # SMTP password (base64 encoded)
  SMTP_PASSWORD: <base64-encoded-smtp-password>
