apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- app-statefulset.yaml

commonLabels:
  app.kubernetes.io/name: aws-resource-watcher
  app.kubernetes.io/version: v1.0.0

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
