apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aws-resource-watcher-redis
  namespace: myapp
  labels:
    app: aws-resource-watcher-redis
spec:
  serviceName: "aws-resource-watcher-redis"
  replicas: 1
  selector:
    matchLabels:
      app: aws-resource-watcher-redis
  template:
    metadata:
      labels:
        app: aws-resource-watcher-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --save
        - "60 1"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: aws-resource-watcher-redis
  namespace: myapp
  labels:
    app: aws-resource-watcher-redis
spec:
  clusterIP: None
  selector:
    app: aws-resource-watcher-redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
